---
- name: Pull docker image of Customised Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull patelparth17/calcproj

    - name: running container
      shell: docker run -it -d patelparth17/calcproj